# Generated by Django 4.2.4 on 2023-09-30 09:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='number',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CargoInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=150)),
                ('whether_information', models.JSONField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_location', to='cargo.cargo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
