# Generated by Django 4.2.4 on 2023-09-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_cargo_number_cargoinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[(0, 'on the way'), (1, 'Delivered')], default=0, max_length=2),
        ),
    ]
