# Generated by Django 4.2.4 on 2023-09-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_cargo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cargos', to='cargo.carrier'),
        ),
    ]
