# Generated by Django 4.2.4 on 2023-09-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_alter_cargo_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[(0, 'processing'), (1, 'on the way'), (2, 'Delivered')], default=0, max_length=2),
        ),
    ]
