# Generated by Django 4.2.4 on 2023-09-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_alter_cargo_number_alter_cargo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
