# Generated by Django 4.2.4 on 2023-09-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_alter_cargo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
