# Generated by Django 4.2.4 on 2023-09-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0007_alter_cargo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('on the way', 'On The Way'), ('Delivered', 'Delivered')], default='processing', max_length=20),
        ),
    ]
