# Generated by Django 4.2.4 on 2023-09-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0008_alter_cargo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[('on the way', 'On The Way'), ('Delivered', 'Delivered')], default='on the way', max_length=20),
        ),
    ]
