# Generated by Django 4.2.4 on 2023-09-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0010_article_articleinformation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name_of_cargo',
            new_name='name_of_article',
        ),
    ]
